#!/bin/bash

msg="drop: assert: [\$BCHK_CFG_DROP_BOX] == [$BCHK_CFG_DROP_BOX] is a folder"
err=0
[  -d "${BCHK_CFG_DROP_BOX}" ] && { bchk.pass $msg ; } || { bchk.fail $msg ; err=1 ; }
[  -d "${BCHK_CFG_DROP_S1}"  ] && { bchk.pass $msg ; } || { bchk.fail $msg ; err=1 ; }
exit "$err"



