#!/bin/bash

case .${1} in
    .|.-h|.--help|.help)
        shift
        arf-help $*
        exit
        ;;
    .--arf)
        shift
        [ "$1" == "" ] && ls ${BCHK_ROOT}/bin || arf-$*
        ;;
    *)
        ${BCHK_APPS}/main $*
        exit $?
        ;;
esac



