#!/bin/bash
which .hackbin > /dev/null || { export PATH=${PATH}:${BCHK_ROOT}/bin ; }

case .${1} in
    .|.-h|.--help|.help)
        shift
        arf-help $*
        exit
        ;;
    .--arf)
        shift
        arf-$*
        exit
        ;;
    *)
        ${BCHK_APPS}/main $*
        exit $?
        ;;
esac



