#!/bin/bash
#arf-doit $0 $*
target=$1
store=./$RANDOM.remove.me
for ii in $(find .); do 
    [ -f $ii ] || continue
    cat $ii | grep "$target" > $store || continue
    echo --$ii
    cat $store
done
rm *.remove.me
