#!/do/not/exec/sh
export BCH_HACK_ROOT=${PWD}
export BCH_HACK_APPS=${BCH_HACK_ROOT}/apps
export BCH_HACK_NAME=bch-hack
main=${PWD}/main
link=${HOME}/.local/bin/${BCH_HACK_NAME}

mkdir -p   ${HOME}/.local/bin
rm         ${link}
echo '$BCH_HACK_ROOT/main $*'  >  ${link}
chmod +x   ${link}

cd ./source.d
for script in $(/bin/ls [0-9]* | sort); do
    _myborg source  $PWD/$script
done
