#!/do/not/exec/sh
export BCHK_ROOT=${PWD}
export BCHK_APPS=${BCHK_ROOT}/apps
export BCHK_NAME=bchk
main=${PWD}/main
link=${HOME}/.local/bin/${BCHK_NAME}

mkdir -p   ${HOME}/.local/bin
rm         ${link}
echo '$BCHK_ROOT/main $*'  >  ${link}
chmod +x   ${link}

cd ./source.d
for script in $(/bin/ls [0-9]* | sort); do
    _myborg source  $PWD/$script
done
