#!/do/not/exec/sh

bchk_activate () {
    insitu=${1}/.insitu
    [ -d ${insitu} ] || return 1
    bchk.pass bchk_activate: activating $(basename $1)
    >/dev/null pushd $insitu
    source ./activate
    >/dev/null popd
}

export BCHK_ROOT=$(dirname ${PWD})
export BCHK_APPS=${BCHK_ROOT}/apps
export BCHK_NAME=bchk
export BCHK_LBIN=${HOME}/.local/bin

which .hackbin > /dev/null || {
    export PATH=${PATH}:${BCHK_ROOT}
    export PATH=${PATH}:${BCHK_ROOT}/bin
}

for name in $(ls ${BCHK_APPS}); do
    bchk_activate ${BCHK_APPS}/${name}
done

